# =========================
# CATEGORIZE CONFIGURATION
# =========================

NUM_TYPES: 2
THRESHOLD: 0.65
BETA: 0.8
EPSILON: 0.05

INPUT_PATH: "data/pdfs"
OUTPUT_PATH: "data/output"

STORAGE:
  INPUT_MODE: "local"        # local / s3
  OUTPUT_MODE: "local"       # local / s3
  S3_INPUT_BUCKET: "my-input-bucket"
  S3_OUTPUT_BUCKET: "my-output-bucket"
  AWS_ACCESS_KEY: "YOUR_AWS_ACCESS_KEY"
  AWS_SECRET_KEY: "YOUR_AWS_SECRET_KEY"
  AWS_REGION: "ap-south-1"

TYPES:
  TYPE_A:
    keywords: ["Invoice No", "GST (18%)", "Date of Purchase", "Total Amount", "Product", "Payment Mode", "Model", "Seller", "IMEI", "Warranty", "Price", "Quantity"]
    weights:  [1.2, 1.1, 1.0, 1.3, 0.9, 1.0, 0.8, 0.9, 1.1, 0.8, 1.0, 0.9]

  TYPE_B:
    keywords: ["Bill No", "Tax Rate", "Invoice Date", "Grand Total", "Item", "Mode Of Payment", "Model Name", "Retailer", "Serial No", "Service Duration", "Rate", "Count"]
    weights:  [1.2, 1.0, 1.1, 1.3, 0.9, 1.0, 0.8, 0.9, 1.1, 0.8, 0.9, 0.8]
